version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://database:27017/ojaswi
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - backend

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
